language: haskell

ghc:
  - 8.6.5

sudo: false

services:
  - docker

before_install:
  - docker pull yandex/clickhouse-server
  - docker run -p 9000:9000 -p 8123:8123 -d --name some-clickhouse-server --ulimit nofile=262144:262144 --rm yandex/clickhouse-server
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack config set system-ghc --global true
  - export PATH=/opt/ghc/8.6.5/bin:$PATH

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.6.5

script:
  - stack --no-terminal --skip-ghc-check test

cache:
  directories:
    - $HOME/.stack
