name:                hdbc-clickhouse
version:             0.1.0.0
github:              "zaneli/hdbc-clickhouse"
license:             BSD3
author:              "zaneli"
maintainer:          "shun.otani@gmail.com"
copyright:           "2020 Shunsuke Otani"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/zaneli/hdbc-clickhouse#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5
- bytestring >= 0.10
- hostname >= 1.0
- network >= 2.8
- iproute >= 1.7
- time >= 1.8
- utf8-string >= 1.0
- HDBC >= 2.2

library:
  source-dirs: src

executables:
  hdbc-clickhouse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hdbc-clickhouse

tests:
  hdbc-clickhouse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hdbc-clickhouse
